# Generated by Django 4.1.13 on 2024-09-03 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuPage', '0002_alter_menupageadministration_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menupageadministration',
            name='color',
            field=models.CharField(choices=[('blue', 'None'), ('blue', 'Blue'), ('green', 'Green'), ('purple', 'Purple'), ('orange', 'Orange')], default='None', max_length=50),
        ),
    ]
