# Generated by Django 4.1.13 on 2024-09-03 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuPage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menupageadministration',
            name='color',
            field=models.CharField(choices=[('None', 'blue'), ('Blue', 'blue'), ('Green', 'green'), ('Purple', 'purple'), ('Orange', 'orange')], default='None', max_length=50),
        ),
    ]
