runtime: python39
entrypoint: gunicorn -b :$PORT restaurantSite.wsgi # Replace 'sharktoothrestaurant' with your Django project name

env_variables:
  DJANGO_SETTINGS_MODULE: "restaurantSite.settings"  # Replace with your project settings
  SECRET_KEY: 'django-insecure-b#h=+3u$@l&3j&swir_ze*rp1#tad7)6usq!_%pghef($q$c77'  # For production, store secrets in Google Secret Manager
  GS_BUCKET_NAME: "restaurantSite"  # Reference to your storage bucket

handlers:
- url: /static
  static_dir: static/

- url: /.*
  script: auto
